### ISSUE TITLE
Incorrect Timezone

### ISSUE THREAD

**Issue by matrixfox** [louixs/tsushin#3]
The small widget is displaying the incorrect timezone. It's 5 hours behind my time. I had to add `useUTC: false` to the xAxis to fix this.

```
    xAxis:
      type: 'datetime'
      dateTimeLabelFormats:
        hour: '%I :%p'
        minute: '%I:%M %p'
        useUTC: false
      #minTickInterval: 600
```
